# Writes the string-name table the UI shell uses to resolve [[TXT_NAME]] references in its
# documents. language.h defines the string identifiers as macros and keeps no name table, so
# every `#define TXT_NAME id` line becomes one entry here.
#
# Run at configure time and once per build, so an edit to language.h reaches the table without
# a reconfigure. The header is only rewritten when its contents change, so an ordinary rebuild
# does not force a recompile.
#
# Expects OPENTS_LANGUAGE_HEADER and OPENTS_STRINGS_HEADER to be set.

if(NOT EXISTS "${OPENTS_LANGUAGE_HEADER}")
    message(FATAL_ERROR "StringTable.cmake: ${OPENTS_LANGUAGE_HEADER} does not exist.")
endif()

file(STRINGS "${OPENTS_LANGUAGE_HEADER}" lines REGEX "^#define TXT_[A-Za-z0-9_]+[ \t]+[0-9]+")

set(entries "")
set(count 0)
foreach(line IN LISTS lines)
    string(REGEX REPLACE "^#define (TXT_[A-Za-z0-9_]+)[ \t]+([0-9]+).*$" "\\1;\\2" parts "${line}")
    list(GET parts 0 name)
    list(GET parts 1 id)
    string(APPEND entries "\t{ \"${name}\", ${id} },\n")
    math(EXPR count "${count} + 1")
endforeach()

if(count EQUAL 0)
    message(FATAL_ERROR "StringTable.cmake: ${OPENTS_LANGUAGE_HEADER} defines no TXT_ identifiers.")
endif()

set(content
"/*******************************************************************************
 *                                O P E N  T S
 *******************************************************************************
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright 2026 OpenTS contributors
 *
 * See LICENSE.md for applicable additional terms and warranty disclaimers.
 ******************************************************************************/

/* Generated by cmake/StringTable.cmake from language.h. Edits are overwritten by the next build. */

#pragma once

struct OpenTSStringName
{
	char const * Name;
	int Id;
};

inline constexpr OpenTSStringName OpenTSStringNames[] = {
${entries}};

inline constexpr int OpenTSStringNameCount = ${count};
")

set(existing "")
if(EXISTS "${OPENTS_STRINGS_HEADER}")
    file(READ "${OPENTS_STRINGS_HEADER}" existing)
endif()

if(NOT existing STREQUAL content)
    file(WRITE "${OPENTS_STRINGS_HEADER}" "${content}")
endif()
