#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2026 OpenTS contributors
"""Writes the INI checker's key catalog from manual/data/ini-keys.yaml.

Each output line holds one scope as tab separated fields: key, file, section,
applies-to list and value type. The section is the literal section name, "*"
for an object section, or "@" and the section source for a section the checker
cannot place. A key holding a range such as "Weapon{1-18}" stands for every key
the engine builds from a number in that range. A lower bound with a leading zero, as in
"Tile{01-}Anim", stands for a number printed with at least that many digits.
"""

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]

# Keys the engine builds from a number that the manual's extractor does not list. Each range
# starts where the reading loop starts; the loops end at NumberOfDocks, Upgrades and TilesInSet,
# which have no fixed limit.
PATTERN_SCOPES = [
    # BuildingTypeClass::Read_INI.
    ("DockingOffset{0-}", "art.ini", "@image", ["BuildingType"], "point (x,y,z)"),
    ("PowerUp{1-}Anim", "art.ini", "@image", ["BuildingType"], "string"),
    ("PowerUp{1-}DamagedAnim", "art.ini", "@image", ["BuildingType"], "string"),
    ("PowerUp{1-}LocXX", "art.ini", "@image", ["BuildingType"], "integer"),
    ("PowerUp{1-}LocYY", "art.ini", "@image", ["BuildingType"], "integer"),
    ("PowerUp{1-}LocZZ", "art.ini", "@image", ["BuildingType"], "integer"),
    ("PowerUp{1-}YSort", "art.ini", "@image", ["BuildingType"], "integer"),
    # IsometricTileTypeClass loading: the keys of a tile set, numbered from 1 as "%02d", up to the
    # set's TilesInSet. A lower bound written with a leading zero stands for that printed width.
    ("Tile{01-}Anim", "theater control file", "@tile-set", ["tile controls"], "string"),
    ("Tile{01-}XOffset", "theater control file", "@tile-set", ["tile controls"], "integer"),
    ("Tile{01-}YOffset", "theater control file", "@tile-set", ["tile controls"], "integer"),
    ("Tile{01-}AttachesTo", "theater control file", "@tile-set", ["tile controls"], "integer"),
    ("Tile{01-}ZAdjust", "theater control file", "@tile-set", ["tile controls"], "integer"),
]


def section_field(section):
    kind = section.get("kind")
    if kind == "literal":
        return section["name"]
    if kind == "identifier" and section.get("source") == "object-type":
        return "*"
    return "@" + str(section.get("source") or kind)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--keys", type=Path, default=ROOT / "manual/data/ini-keys.yaml")
    parser.add_argument("--output", type=Path, help="file to write; standard output when omitted")
    args = parser.parse_args()

    with args.keys.open(encoding="utf-8") as stream:
        catalog = yaml.safe_load(stream)

    lines = ["# Generated by tools/inicheck/export_catalog.py; do not edit."]
    for name in sorted(catalog):
        for scope in catalog[name]["scopes"]:
            fields = [
                catalog[name]["key"],
                scope["file"],
                section_field(scope["section"]),
                ",".join(scope.get("applies_to") or []),
                scope.get("value_type") or "",
            ]
            if any("\t" in field or "\n" in field for field in fields):
                sys.exit(f"{name}: a field holds a tab or line break")
            lines.append("\t".join(fields))
    for key, file, section, applies_to, value_type in PATTERN_SCOPES:
        lines.append("\t".join([key, file, section, ",".join(applies_to), value_type]))

    text = "\n".join(lines) + "\n"
    if args.output:
        args.output.write_text(text, encoding="utf-8", newline="\n")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
