#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2026 OpenTS contributors
"""Writes the INI checker's key catalog from manual/data/ini-keys.yaml.

Each output line holds one scope as tab separated fields: key, file, section,
applies-to list and value type. The section is the literal section name, "*"
for an object section, or "@" and the section source for a section the checker
cannot place.
"""

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]


def section_field(section):
    kind = section.get("kind")
    if kind == "literal":
        return section["name"]
    if kind == "identifier" and section.get("source") == "object-type":
        return "*"
    return "@" + str(section.get("source") or kind)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--keys", type=Path, default=ROOT / "manual/data/ini-keys.yaml")
    parser.add_argument("--output", type=Path, help="file to write; standard output when omitted")
    args = parser.parse_args()

    with args.keys.open(encoding="utf-8") as stream:
        catalog = yaml.safe_load(stream)

    lines = ["# Generated by tools/inicheck/export_catalog.py; do not edit."]
    for name in sorted(catalog):
        for scope in catalog[name]["scopes"]:
            fields = [
                catalog[name]["key"],
                scope["file"],
                section_field(scope["section"]),
                ",".join(scope.get("applies_to") or []),
                scope.get("value_type") or "",
            ]
            if any("\t" in field or "\n" in field for field in fields):
                sys.exit(f"{name}: a field holds a tab or line break")
            lines.append("\t".join(fields))

    text = "\n".join(lines) + "\n"
    if args.output:
        args.output.write_text(text, encoding="utf-8", newline="\n")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
